server:
  port : 8082

spring:
  # Rabbitmq config
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

  # Kafka broker config
  cloud.stream.kafka.binder.brokers: localhost:9092

  # stream function bindings
  cloud.stream.function:
    definitions: processor
    bindings:
      processor-in-0: inbound
      processor-out-0: outbound

  # stream bindings config
  cloud.stream.bindings:
      inbound:
        group: publish
        destination: published # kafka topic to listen to
        binder: kafka
      outbound:
        destination: start # rabbitmq exchange/topic to send messages to
        binder: rabbit

rdpc:
  url: https://api.rdpc-dev.cancercollaboratory.org/graphql
